"""
RFC 5545 iCalendar (.ics) Generator Tool.
Exports optimized itineraries directly into standard calendar event files
compatible with Google Calendar, Apple Calendar, and Microsoft Outlook.
"""
from datetime import datetime, timedelta
from pathlib import Path
from typing import Optional
from icalendar import Calendar, Event, Alarm
from models.schemas import TripPlan


def generate_trip_ics(trip_plan: TripPlan, output_path: Optional[Path] = None) -> Path:
    """
    Generates a standard .ics calendar file for the entire trip.
    Each time slot becomes a scheduled calendar event with location, notes, and reminders.
    """
    cal = Calendar()
    cal.add('prodid', '-//Smart Tourist Attraction Recommendation Agent//mxm.dk//')
    cal.add('version', '2.0')
    cal.add('x-wr-calname', f"{trip_plan.profile.destination.title()} Trip Itinerary")

    # Use current or upcoming base date
    base_date = datetime.now() + timedelta(days=1)

    for day in trip_plan.days:
        day_date = base_date + timedelta(days=day.day_number - 1)

        for slot in day.time_slots:
            try:
                # Parse "09:00" -> datetime
                start_h, start_m = map(int, slot.start_time.split(":"))
                end_h, end_m = map(int, slot.end_time.split(":"))

                dt_start = day_date.replace(hour=start_h, minute=start_m, second=0, microsecond=0)
                dt_end = day_date.replace(hour=end_h, minute=end_m, second=0, microsecond=0)

                event = Event()
                event.add('summary', f"📍 {slot.activity_name}")
                
                desc = f"Activity: {slot.activity_name}\n"
                desc += f"Time Slot: {slot.slot_type} ({slot.start_time} - {slot.end_time})\n"
                if slot.notes:
                    desc += f"Notes: {slot.notes}\n"
                if slot.cost > 0:
                    desc += f"Entry/Meal Cost: {trip_plan.profile.currency}{slot.cost:,.0f}\n"
                if slot.transit_mins > 0:
                    desc += f"Transit: {slot.transit_mins} mins via {slot.transit_mode}\n"
                if slot.crowd_forecast:
                    desc += f"Expected Crowd: {slot.crowd_forecast}\n"
                desc += f"\nGenerated by Smart Tourist Attraction Recommendation Agent."

                event.add('description', desc)
                event.add('dtstart', dt_start)
                event.add('dtend', dt_end)

                if slot.attraction and slot.attraction.address:
                    event.add('location', slot.attraction.address)
                else:
                    event.add('location', f"{trip_plan.profile.destination.title()}")

                # 15-minute prior reminder alarm
                alarm = Alarm()
                alarm.add('action', 'DISPLAY')
                alarm.add('description', f"Upcoming: {slot.activity_name}")
                alarm.add('trigger', timedelta(minutes=-15))
                event.add_component(alarm)

                cal.add_component(event)
            except Exception:
                continue

    if output_path is None:
        from config import settings
        output_path = settings.OUTPUT_DIR / f"{trip_plan.trip_id}.ics"

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'wb') as f:
        f.write(cal.to_ical())

    return output_path
